### ISSUE TITLE
A problem in lines  #call HYPHY

### ISSUE THREAD

**Issue by xiayh17** [KseniaJuravel/Positive-Selection-with-HYPHY#2]
Many thanks for your work in these script.
But I have encountered some problems in the operation and don't know how to solve it.
this is the error log

Error:Unexpected symbol  in the following context: '#<ERROR HERE>!/bin/bashinputRedirect='

And I run it line by line, I think it is caused by the command HYPHYMP MEME_batch.bf;
I copied the information displayed on the terminal below.

$ HYPHYMP MEME_batch.bf;
Error:
Unexpected symbol  in the following context: '#<ERROR HERE>!/bin/bashinputRedirect='

Function call stack
1 : #!/bin/bashinputRedirect={}
-------

Check errors.log for details on execution errors.

Check messages.log details of this run._

Thank you again for your useful code, and I really hope to solve this problem.

**Comment by xiayh17** [comment]
Hi, 
I think this issues can be closed.
It runs perfect after I DELETE ALL Word Annotated with # in the .bf files.
Thanks again.

**Comment by KseniaJuravel** [comment]
Hi, sorry for the late reply, had some big changes going on.
Hope it works well now, feel free to ask if needed in the future and good luck with your work :) @xiayh1
